settings_version: 0.0.4
datasets_dir: C:\Users\Kavya\OneDrive\Desktop\smart waste\ai-model\datasets
weights_dir: weights
runs_dir: runs
uuid: f5707d2da1b7ad0e81320548559039b517232b12d673f1245809a407034fa3bb
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
